name: BSHongbao
version: '${version}'
main: com.bSHongbao.BSHongbao
# 提升到 1.20 确保兼容性
api-version: '1.20'
# 必须添加此行，Folia 才会加载插件
folia-supported: true
author: sigmoid
description: 'A red packet plugin for Minecraft servers'
depend: [Vault]

commands:
  BSHongbao:
    description: 'Open red packet GUI'
    usage: '/BSHongbao open'
    permission: bshongbao.use
    aliases: [hongbao, redpacket]
  # 隐藏领取命令，防止玩家手动输入
  bshongbao_claim:
    description: '领取红包命令'
    permission: bshongbao.use

permissions:
  bshongbao.use:
    description: 'Allows player to use red packet commands'
    default: true
  bshongbao.admin:
    description: 'Allows player to manage red packets'
    default: op