name: BSHongbao
version: '2.0.0'
main: top.wunanc.bSHongbao.BSHongbao
api-version: '1.21'
authors: [ Hotguo ]
description: A plugin that provides a 'red envelope' feature for Minecraft servers, supporting both regular red envelopes and lucky draw red envelopes. It integrates with Vault economy, comes with a visual GUI, and includes automatic expiration refunds and concurrency-safe design.
website: wunanc.top
